

Exercise.create([
    { name: "Hollow Sit", video: "http://www.youtube.com/watch?v=sYwm8VqAl2U", hold: "15 sec", reps: "1" },
    { name: "V-Up", video: "http://www.youtube.com/watch?v=oFtdpmN7kJ4", hold: "X", reps: "10" },
    { name: "V-Up", video: "http://www.youtube.com/watch?v=oFtdpmN7kJ4", hold: "1 sec", reps: "10" },
    { name: "V-Up", video: "http://www.youtube.com/watch?v=oFtdpmN7kJ4", hold: "1 sec", reps: "15" },
    { name: "V-Up", video: "http://www.youtube.com/watch?v=oFtdpmN7kJ4", hold: "X", reps: "50" },
    { name: "Suitcase Crunch", video: "http://youtu.be/Btd5NSScfSg", hold: "1 sec", reps: "20" },
    { name: "Suitcase Crunch", video: "http://youtu.be/Btd5NSScfSg", hold: "X", reps: "20" },
    { name: "Suitcase Crunch", video: "http://youtu.be/Btd5NSScfSg", hold: "1 sec", reps: "30" },
    { name: "Suitcase Crunch", video: "http://youtu.be/Btd5NSScfSg", hold: "1 sec", reps: "10" },
    { name: "Leg Raise", video: "http://youtu.be/9KUb52nTnhw", hold: "1 sec", reps: "20" },
    { name: "Leg Raise", video: "http://youtu.be/9KUb52nTnhw", hold: "1 sec", reps: "10" },
    { name: "Leg Raise", video: "http://youtu.be/9KUb52nTnhw", hold: "X", reps: "10" },
    { name: "Leg Raise", video: "http://youtu.be/9KUb52nTnhw", hold: "1 sec", reps: "30" },
    { name: "Leg Raise", video: "http://youtu.be/9KUb52nTnhw", hold: "1 sec", reps: "MAX" },
    { name: "Reverse Lunge - Right Leg", video: "http://www.youtube.com/watch?v=7EPImHHY49c", hold: "15 sec*", reps: "1" },
    { name: "Reverse Lunge", video: "http://www.youtube.com/watch?v=7EPImHHY49c", hold: "1 sec", reps: "10 R/L" },
    { name: "Reverse Lunge - Left Leg", video: "http://www.youtube.com/watch?v=7EPImHHY49c", hold: "15 sec*", reps: "1" },
    { name: "Lateral Lunge", video: "http://youtu.be/45efi4CgFsw", hold: "1 sec", reps: "10 R/L" },
    { name: "Airborne Lunge", video: "http://youtu.be/rQ8oxNv4f8M", hold: "1 sec", reps: "10 R/L" },
    { name: "Airborne Lunge", video: "http://youtu.be/rQ8oxNv4f8M", hold: "1 sec", reps: "7 R/L" },
    { name: "Side Bridge", video: "http://www.youtube.com/watch?v=yXYJxo7A9h0", hold: "30 sec", reps: "1 R/L" },
    { name: "Side Bridge - Knee Tuck", video: "http://youtu.be/LUil8oZopg8", hold: "1 sec", reps: "10 R/L" },
    { name: "Side Bridge - Leg Lift", video: "http://youtu.be/VZr_2ZdkyQQ", hold: "3 sec", reps: "5 R/L" },
    { name: "Side Bridge - Leg Lift", video: "http://youtu.be/VZr_2ZdkyQQ", hold: "1 sec", reps: "10 R/L" },
    { name: "Side Bridge - Leg Lift", video: "http://youtu.be/VZr_2ZdkyQQ", hold: "1 sec", reps: "15 R/L" },
    { name: "Front Bridge", video: "http://www.youtube.com/watch?v=fNrQqj49hmM", hold: "30 sec", reps: "1" },
    { name: "Front Bridge - Hi/Low", video: "http://youtu.be/18OdmaEO-A4", hold: "1 sec", reps: "10" },
    { name: "Front Bridge Knee-To-Elbow", video: "http://youtu.be/Z6EXskY_nQw", hold: "X", reps: "10 R/L" },
    { name: "Front Bridge Knee-To-Elbow", video: "http://youtu.be/Z6EXskY_nQw", hold: "3 sec", reps: "5 R/L" },
    { name: "Front Bridge - Spread Eagle", video: "http://youtu.be/QIQnKdFz5xw", hold: "X", reps: "10" },
    { name: "Glute Bridge", video: "http://www.youtube.com/watch?v=XoSyjdemIko", hold: "1 sec", reps: "20" },
    { name: "Glute Bridge - Marching", video: "http://youtu.be/uF-DzZlbKr0", hold: "1 sec", reps: "10 R/L" },
    { name: "Glute Bridge", video: "http://www.youtube.com/watch?v=XoSyjdemIko", hold: "1 sec", reps: "30" },
    { name: "1 Leg Glute Bridge", video: "http://youtu.be/4a95Eif8R0I", hold: "3 sec", reps: "5 R/L" },
    { name: "1 Leg Glute Bridge", video: "http://youtu.be/4a95Eif8R0I", hold: "1 sec", reps: "10 R/L" },
    { name: "Push-Up", video: "http://www.youtube.com/watch?v=nwhO5fuN8kE", hold: "1 sec", reps:"10" },
    { name: "Push-Up", video: "http://www.youtube.com/watch?v=nwhO5fuN8kE", hold: "15 sec*", reps:"1"},
    { name: "Push-Up", video: "http://www.youtube.com/watch?v=nwhO5fuN8kE", hold: "1 sec", reps:"15"},
    { name: "Push-Up", video: "http://www.youtube.com/watch?v=nwhO5fuN8kE", hold: "X", reps:"10"},
    { name: "Push-Up", video: "http://www.youtube.com/watch?v=nwhO5fuN8kE", hold: "1 sec", reps:"5"},
    { name: "Push-Up", video: "http://www.youtube.com/watch?v=nwhO5fuN8kE", hold: "1 sec", reps:"20,16,12..." },
    { name: "Push-Up", video: "http://www.youtube.com/watch?v=nwhO5fuN8kE", hold: "X", reps:"14"},
    { name: "Push-Up", video: "http://www.youtube.com/watch?v=nwhO5fuN8kE", hold: "1 sec", reps:"25"},
    { name: "Close Grip Push-Up", video: "http://youtu.be/er4QyzKYrH8", hold: "1 sec", reps: "10" },
    { name: "Close Grip Push-Up", video: "http://youtu.be/er4QyzKYrH8", hold: "1 sec", reps: "15" },
    { name: "Close Grip Push-Up", video: "http://youtu.be/er4QyzKYrH8", hold: "1 sec", reps: "10,8,6..." },
    { name: "Close Grip Push-Up", video: "http://youtu.be/er4QyzKYrH8", hold: "1 sec", reps: "20" },
    { name: "Close Grip Push-Up", video: "http://youtu.be/er4QyzKYrH8", hold: "1 sec", reps: "MAX" },
    { name: "A Push-Up", video: "http://youtu.be/h4pFpwSXuFA", hold: "1 sec", reps: "10" },
    { name: "A Push-Up", video: "http://youtu.be/h4pFpwSXuFA", hold: "1 sec", reps: "15" },
    { name: "A Push-Up", video: "http://youtu.be/h4pFpwSXuFA", hold: "1 sec", reps: "5,4,3..." },
    { name: "A Push-Up", video: "http://youtu.be/h4pFpwSXuFA", hold: "1 sec", reps: "6" },
    { name: "A Push-Up", video: "http://youtu.be/h4pFpwSXuFA", hold: "1 sec", reps: "12" },
    { name: "Squat", video: "http://www.youtube.com/watch?v=-J8OOtEqFtg", hold: "1 sec", reps: "20" },
    { name: "Squat", video: "http://www.youtube.com/watch?v=-J8OOtEqFtg", hold: "30 sec*", reps: "1" },
    { name: "Squat", video: "http://www.youtube.com/watch?v=-J8OOtEqFtg", hold: "1 sec", reps: "20,16,12..."},
    { name: "Squat", video: "http://www.youtube.com/watch?v=-J8OOtEqFtg", hold: "1 sec", reps: "21"},
    { name: "Squat", video: "http://www.youtube.com/watch?v=-J8OOtEqFtg", hold: "1 sec", reps: "50"},
    { name: "Squat Jump", video: "http://www.youtube.com/watch?v=0fNHXgseCtI", hold: "X", reps: "10" },
    { name: "Squat Jump", video: "http://www.youtube.com/watch?v=0fNHXgseCtI", hold: "X", reps: "5*" },
    { name: "Squat Jump", video: "http://www.youtube.com/watch?v=0fNHXgseCtI", hold: "X", reps: "10,8,6..." },
    { name: "Squat Jump", video: "http://www.youtube.com/watch?v=0fNHXgseCtI", hold: "X", reps: "9" },
    { name: "Squat Jump", video: "http://www.youtube.com/watch?v=0fNHXgseCtI", hold: "X", reps: "X" },
    { name: "Split Squat Jump", video: "http://www.youtube.com/watch?v=bry_0XMxQKg", hold: "1 sec", reps: "10 R/L" },
    { name: "Split Squat Jump", video: "http://www.youtube.com/watch?v=bry_0XMxQKg", hold: "X", reps: "X" },
    { name: "Split Squat Jump", video: "http://www.youtube.com/watch?v=bry_0XMxQKg", hold: "X", reps: "MAX" },
    { name: "Split Squat Jump", video: "http://www.youtube.com/watch?v=bry_0XMxQKg", hold: "X", reps: "50 R/L" },
    { name: "Split Squat RFE", video: "http://youtu.be/J6G2mAHiL3A",hold: "1 sec", reps: "10 R/L" },
    { name: "Split Squat RFE", video: "http://youtu.be/J6G2mAHiL3A",hold: "1 sec", reps: "50 R/L" },
    { name: "1 Leg Squat", video: "http://youtu.be/_X421gYXZ3U", hold: "1 sec", reps: "5 R/L"},
    { name: "1 Leg Squat", video: "http://youtu.be/_X421gYXZ3U", hold: "1 sec", reps: "10 R/L"},
    { name: "Pistol Squat", video: "http://youtu.be/dejEOHNkPzs", hold: "1 sec", reps: "5 R/L" },
    { name: "Pistol Squat", video: "http://youtu.be/dejEOHNkPzs", hold: "1 sec", reps: "5,4,3..." },
    { name: "Pistol Squat", video: "http://youtu.be/dejEOHNkPzs", hold: "1 sec", reps: "3 R/L" },
    { name: "Pistol Squat", video: "http://youtu.be/dejEOHNkPzs", hold: "1 sec", reps: "6 R/L" },
    { name: "Y", video: "http://www.youtube.com/watch?v=o4R-lG5wUSA", hold: "15 sec", reps: "1" },
    { name: "Y", video: "http://www.youtube.com/watch?v=o4R-lG5wUSA", hold: "1 sec", reps: "15" },
    { name: "W", video: "http://www.youtube.com/watch?v=rLTP7HCUlMg", hold: "15 sec", reps: "1" },
    { name: "W", video: "http://www.youtube.com/watch?v=rLTP7HCUlMg", hold: "1 sec", reps: "10" },
    { name: "W", video: "http://www.youtube.com/watch?v=rLTP7HCUlMg", hold: "1 sec", reps: "20" },
    { name: "W", video: "http://www.youtube.com/watch?v=rLTP7HCUlMg", hold: "X", reps: "10" },
    { name: "Jumping Jack", video: "http://www.youtube.com/watch?v=aUHZeLYA6VU", hold: "X", reps: "20" },
    { name: "Jumping Jack", video: "http://www.youtube.com/watch?v=aUHZeLYA6VU", hold: "X", reps: "40" },
    { name: "I-T", video: "http://youtu.be/J5j-SyejqZw", hold: "1 sec", reps: "10" },
    { name: "I-T", video: "http://youtu.be/J5j-SyejqZw", hold: "1 sec", reps: "15" },
    { name: "Bear Claw", video: "http://youtu.be/hXCwH7GWQBA", hold: "3 sec", reps: "5 R/L" },
    { name: "Y-W", video: "http://youtu.be/mRix5boe6AQ", hold: "1 sec", reps: "10" },
    { name: "Y-W", video: "http://youtu.be/mRix5boe6AQ", hold: "1 sec", reps: "5" },
    { name: "Y-W", video: "http://youtu.be/mRix5boe6AQ", hold: "1 sec", reps: "15" },
    { name: "Y-W", video: "http://youtu.be/mRix5boe6AQ", hold: "1 sec", reps: "9" },
    { name: "Y-W", video: "http://youtu.be/mRix5boe6AQ", hold: "X", reps: "10" },
    { name: "Shoulder Taps", video: "http://youtu.be/h-9G-zACYho", hold: "3 sec", reps: "5 R/L" },
    { name: "Shoulder Taps", video: "http://youtu.be/h-9G-zACYho", hold: "1 sec", reps: "10 R/L" },
    { name: "Shoulder Taps", video: "http://youtu.be/h-9G-zACYho", hold: "X", reps: "10 R/L" },
    { name: "Shoulder Taps", video: "http://youtu.be/h-9G-zACYho", hold: "X", reps: "20 R/L" },
    { name: "Broad Jump", video: "http://youtu.be/ffxkGhSnB4Y", hold: "X", reps: "5*" },
    { name: "Broad Jump", video: "http://youtu.be/ffxkGhSnB4Y", hold: "X", reps: "10" },
    { name: "Burpee", video: "http://youtu.be/aMnhI8P6ijw", hold: "X", reps: "50" },
    { name: "Burpee", video: "http://youtu.be/aMnhI8P6ijw", hold: "X", reps: "5" },
    { name: "Burpee", video: "http://youtu.be/aMnhI8P6ijw", hold: "X", reps: "10" },
    { name: "Lateral Bound", video: "http://youtu.be/QcQ9w0O3ujw", hold: "1 sec", reps: "10 R/L" },
    { name: "Lateral Bound", video: "http://youtu.be/QcQ9w0O3ujw", hold: "X", reps: "10 R/L" },
    { name: "Lateral Bound", video: "http://youtu.be/QcQ9w0O3ujw", hold: "X", reps: "X" },
    { name: "Lateral Bound", video: "http://youtu.be/QcQ9w0O3ujw", hold: "X", reps: "MAX" },
    { name: "Mountain Climber", video: "http://youtu.be/zEplDzou308", hold: "X", reps: "10 R/L" },
    { name: "Mountain Climber", video: "http://youtu.be/zEplDzou308", hold: "X", reps: "X" },
    { name: "Mountain Climber", video: "http://youtu.be/zEplDzou308", hold: "X", reps: "50 R/L" },
    { name: "Superman", video: "http://youtu.be/n4bGLnAyyqY", hold: "3 sec", reps: "10" },
    { name: "Box Blast", video: "http://youtu.be/AaGfyHYB7y8", hold: "X", reps: "10 R/L" },
    { name: "High Knee Skip - In Place",video: "http://youtu.be/EEGrjye9eag", hold: "X", reps: "20 R/L" }
])
