Challenge.create!([
  {name: "Memorial Day Challenge", start_date: "2015-05-25", current_day: 9}
])
Program.create!([
  {name: "Shredzilla"},
  {name: "Beastzilla"},
  {name: "Fitzilla"},
  {name: "Strongzilla"}
])
Day.create!([
  {program_id: 1, day: 1, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 2, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 3, description: "Rest, Stretch, Plan Meals, or make up a workout from earlier in the week.", option_1: nil, option_2: nil},
  {program_id: 1, day: 4, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 5, description: nil, option_1: "Sprint 30 sec / Rest 30 sec - 10 sets", option_2: "Run as far as you can in 10:00 - walk back"},
  {program_id: 1, day: 6, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 7, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 1, day: 8, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 9, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 10, description: "Rest Day - Do a make up workout, stretch, or plan meals for the week.", option_1: nil, option_2: nil},
  {program_id: 1, day: 11, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 12, description: nil, option_1: "Sprint 30 sec / Rest 30 sec - 15 sets", option_2: "Run 10:00 - try and beat distance from last week (walk back)"},
  {program_id: 1, day: 13, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 14, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 1, day: 15, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 16, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 17, description: "Rest day - Stretch, Roll Out, Plan Meals for the week, or make up a workout.", option_1: nil, option_2: nil},
  {program_id: 1, day: 18, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 19, description: "Tempo Runs: Sprint 100Yds - 20 sets (one set every :40). Try to complete each set in :20 and rest :20", option_1: nil, option_2: nil},
  {program_id: 1, day: 20, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 21, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 1, day: 22, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 23, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 24, description: "Rest day - Stretch, Roll Out, Plan Meals for the week, or make up a workout.", option_1: nil, option_2: nil},
  {program_id: 1, day: 25, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 26, description: "Tempo Runs: Sprint 100Yds - 30 sets (one set every :40). Try to complete each set in :20 and rest :20", option_1: nil, option_2: nil},
  {program_id: 1, day: 27, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 28, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 1, day: 29, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 30, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 31, description: "Rest Day - Do a make up workout, stretch, or plan meals for the week.", option_1: nil, option_2: nil},
  {program_id: 1, day: 32, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 33, description: "60 Yd Shuttle - 20 Sets(one every :30) / Shuttle Run: 5 Yd - Back - 10 Yd - Back - 15 Yd - Back / Try to complete each set in :15 and rest :15", option_1: nil, option_2: nil},
  {program_id: 1, day: 34, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 35, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 1, day: 36, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 37, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 38, description: "Rest day - Stretch, Roll Out, Plan Meals for the week, or make up a workout.", option_1: nil, option_2: nil},
  {program_id: 1, day: 39, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 40, description: "60 Yd Shuttle - 20 Sets(one every :30) / Shuttle Run: 5 Yd - Back - 10 Yd - Back - 15 Yd - Back / Try to complete each set in :15 and rest :15", option_1: nil, option_2: nil},
  {program_id: 1, day: 41, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 42, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 1, day: 43, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 44, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 45, description: "Rest day - Stretch, Roll Out, Plan Meals for the week, or make up a workout.", option_1: nil, option_2: nil},
  {program_id: 1, day: 46, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 47, description: "400m Sprints - 4 sets - Take full recovery between each", option_1: nil, option_2: nil},
  {program_id: 1, day: 48, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 49, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 1, day: 50, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 51, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 52, description: "Rest day - Stretch, Roll Out, Plan Meals for the week, or make up a workout.", option_1: nil, option_2: nil},
  {program_id: 1, day: 53, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 54, description: "400m Sprint - 6 sets - Take full recovery between each", option_1: nil, option_2: nil},
  {program_id: 1, day: 55, description: nil, option_1: nil, option_2: nil},
  {program_id: 1, day: 56, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 1, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 2, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 3, description: "Rest, Stretch, Plan Meals, or make up a workout from earlier in the week.", option_1: nil, option_2: nil},
  {program_id: 2, day: 4, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 5, description: nil, option_1: "Sprint 30 sec / Rest 30 sec - 10 sets", option_2: "Run as far as you can in 10:00 - walk back"},
  {program_id: 2, day: 6, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 7, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 2, day: 8, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 9, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 10, description: "Rest Day - Do a make up workout, stretch, or plan meals for the week.", option_1: nil, option_2: nil},
  {program_id: 2, day: 11, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 12, description: nil, option_1: "Sprint 30 sec / Rest 30 sec - 15 sets", option_2: "Run 10:00 - try and beat distance from last week (walk back)"},
  {program_id: 2, day: 13, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 14, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 2, day: 15, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 16, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 17, description: "Rest day - Stretch, Roll Out, Plan Meals for the week, or make up a workout.", option_1: nil, option_2: nil},
  {program_id: 2, day: 18, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 19, description: "Tempo Runs: Sprint 100Yds - 20 sets (one set every :40). Try to complete each set in :20 and rest :20", option_1: nil, option_2: nil},
  {program_id: 2, day: 20, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 21, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 2, day: 22, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 23, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 24, description: "Rest day - Stretch, Roll Out, Plan Meals for the week, or make up a workout.", option_1: nil, option_2: nil},
  {program_id: 2, day: 25, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 26, description: "Tempo Runs: Sprint 100Yds - 30 sets (one set every :40). Try to complete each set in :20 and rest :20", option_1: nil, option_2: nil},
  {program_id: 2, day: 27, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 28, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 2, day: 29, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 30, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 31, description: "Rest Day - Do a make up workout, stretch, or plan meals for the week.", option_1: nil, option_2: nil},
  {program_id: 2, day: 32, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 33, description: "60 Yd Shuttle - 20 Sets(one every :30) / Shuttle Run: 5 Yd - Back - 10 Yd - Back - 15 Yd - Back / Try to complete each set in :15 and rest :15", option_1: nil, option_2: nil},
  {program_id: 2, day: 34, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 35, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 2, day: 36, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 37, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 38, description: "Rest day - Stretch, Roll Out, Plan Meals for the week, or make up a workout.", option_1: nil, option_2: nil},
  {program_id: 2, day: 39, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 40, description: "60 Yd Shuttle - 20 Sets(one every :30) / Shuttle Run: 5 Yd - Back - 10 Yd - Back - 15 Yd - Back / Try to complete each set in :15 and rest :15", option_1: nil, option_2: nil},
  {program_id: 2, day: 41, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 42, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 2, day: 43, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 44, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 45, description: "Rest day - Stretch, Roll Out, Plan Meals for the week, or make up a workout.", option_1: nil, option_2: nil},
  {program_id: 2, day: 46, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 47, description: "400m Sprints - 4 sets - Take full recovery between each", option_1: nil, option_2: nil},
  {program_id: 2, day: 48, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 49, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 2, day: 50, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 51, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 52, description: "Rest day - Stretch, Roll Out, Plan Meals for the week, or make up a workout.", option_1: nil, option_2: nil},
  {program_id: 2, day: 53, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 54, description: "400m Sprint - 6 sets - Take full recovery between each", option_1: nil, option_2: nil},
  {program_id: 2, day: 55, description: nil, option_1: nil, option_2: nil},
  {program_id: 2, day: 56, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 1, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 2, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 3, description: "Rest, Stretch, Plan Meals, or make up a workout from earlier in the week.", option_1: nil, option_2: nil},
  {program_id: 3, day: 4, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 5, description: nil, option_1: "Sprint 30 sec / Rest 30 sec - 10 sets", option_2: "Run as far as you can in 10:00 - walk back"},
  {program_id: 3, day: 6, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 7, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 3, day: 8, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 9, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 10, description: "Rest Day - Do a make up workout, stretch, or plan meals for the week.", option_1: nil, option_2: nil},
  {program_id: 3, day: 11, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 12, description: nil, option_1: "Sprint 30 sec / Rest 30 sec - 15 sets", option_2: "Run 10:00 - try and beat distance from last week (walk back)"},
  {program_id: 3, day: 13, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 14, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 3, day: 15, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 16, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 17, description: "Rest day - Stretch, Roll Out, Plan Meals for the week, or make up a workout.", option_1: nil, option_2: nil},
  {program_id: 3, day: 18, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 19, description: "Tempo Runs: Sprint 100Yds - 20 sets (one set every :40). Try to complete each set in :20 and rest :20", option_1: nil, option_2: nil},
  {program_id: 3, day: 20, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 21, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 3, day: 22, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 23, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 24, description: "Rest day - Stretch, Roll Out, Plan Meals for the week, or make up a workout.", option_1: nil, option_2: nil},
  {program_id: 3, day: 25, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 26, description: "Tempo Runs: Sprint 100Yds - 30 sets (one set every :40). Try to complete each set in :20 and rest :20", option_1: nil, option_2: nil},
  {program_id: 3, day: 27, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 28, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 3, day: 29, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 30, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 31, description: "Rest Day - Do a make up workout, stretch, or plan meals for the week.", option_1: nil, option_2: nil},
  {program_id: 3, day: 32, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 33, description: "60 Yd Shuttle - 20 Sets(one every :30) / Shuttle Run: 5 Yd - Back - 10 Yd - Back - 15 Yd - Back / Try to complete each set in :15 and rest :15", option_1: nil, option_2: nil},
  {program_id: 3, day: 34, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 35, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 3, day: 36, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 37, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 38, description: "Rest day - Stretch, Roll Out, Plan Meals for the week, or make up a workout.", option_1: nil, option_2: nil},
  {program_id: 3, day: 39, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 40, description: "60 Yd Shuttle - 20 Sets(one every :30) / Shuttle Run: 5 Yd - Back - 10 Yd - Back - 15 Yd - Back / Try to complete each set in :15 and rest :15", option_1: nil, option_2: nil},
  {program_id: 3, day: 41, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 42, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 3, day: 43, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 44, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 45, description: "Rest day - Stretch, Roll Out, Plan Meals for the week, or make up a workout.", option_1: nil, option_2: nil},
  {program_id: 3, day: 46, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 47, description: "400m Sprints - 4 sets - Take full recovery between each", option_1: nil, option_2: nil},
  {program_id: 3, day: 48, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 49, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 3, day: 50, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 51, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 52, description: "Rest day - Stretch, Roll Out, Plan Meals for the week, or make up a workout.", option_1: nil, option_2: nil},
  {program_id: 3, day: 53, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 54, description: "400m Sprint - 6 sets - Take full recovery between each", option_1: nil, option_2: nil},
  {program_id: 3, day: 55, description: nil, option_1: nil, option_2: nil},
  {program_id: 3, day: 56, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 1, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 2, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 3, description: "Rest, Stretch, Plan Meals, or make up a workout from earlier in the week.", option_1: nil, option_2: nil},
  {program_id: 4, day: 4, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 5, description: nil, option_1: "Sprint 30 sec / Rest 30 sec - 10 sets", option_2: "Run as far as you can in 10:00 - walk back"},
  {program_id: 4, day: 6, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 7, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 4, day: 8, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 9, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 10, description: "Rest Day - Do a make up workout, stretch, or plan meals for the week.", option_1: nil, option_2: nil},
  {program_id: 4, day: 11, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 12, description: nil, option_1: "Sprint 30 sec / Rest 30 sec - 15 sets", option_2: "Run 10:00 - try and beat distance from last week (walk back)"},
  {program_id: 4, day: 13, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 14, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 4, day: 15, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 16, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 17, description: "Rest day - Stretch, Roll Out, Plan Meals for the week, or make up a workout.", option_1: nil, option_2: nil},
  {program_id: 4, day: 18, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 19, description: "Tempo Runs: Sprint 100Yds - 20 sets (one set every :40). Try to complete each set in :20 and rest :20", option_1: nil, option_2: nil},
  {program_id: 4, day: 20, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 21, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 4, day: 22, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 23, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 24, description: "Rest day - Stretch, Roll Out, Plan Meals for the week, or make up a workout.", option_1: nil, option_2: nil},
  {program_id: 4, day: 25, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 26, description: "Tempo Runs: Sprint 100Yds - 30 sets (one set every :40). Try to complete each set in :20 and rest :20", option_1: nil, option_2: nil},
  {program_id: 4, day: 27, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 28, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 4, day: 29, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 30, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 31, description: "Rest Day - Do a make up workout, stretch, or plan meals for the week.", option_1: nil, option_2: nil},
  {program_id: 4, day: 32, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 33, description: "60 Yd Shuttle - 20 Sets(one every :30) / Shuttle Run: 5 Yd - Back - 10 Yd - Back - 15 Yd - Back / Try to complete each set in :15 and rest :15", option_1: nil, option_2: nil},
  {program_id: 4, day: 34, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 35, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 4, day: 36, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 37, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 38, description: "Rest day - Stretch, Roll Out, Plan Meals for the week, or make up a workout.", option_1: nil, option_2: nil},
  {program_id: 4, day: 39, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 40, description: "60 Yd Shuttle - 20 Sets(one every :30) / Shuttle Run: 5 Yd - Back - 10 Yd - Back - 15 Yd - Back / Try to complete each set in :15 and rest :15", option_1: nil, option_2: nil},
  {program_id: 4, day: 41, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 42, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 4, day: 43, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 44, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 45, description: "Rest day - Stretch, Roll Out, Plan Meals for the week, or make up a workout.", option_1: nil, option_2: nil},
  {program_id: 4, day: 46, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 47, description: "400m Sprints - 4 sets - Take full recovery between each", option_1: nil, option_2: nil},
  {program_id: 4, day: 48, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 49, description: "One Hour of Play! Walk, hike, go for a bike ride. play ultimate frisbee... Be active and have fun for at least one hour.", option_1: nil, option_2: nil},
  {program_id: 4, day: 50, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 51, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 52, description: "Rest day - Stretch, Roll Out, Plan Meals for the week, or make up a workout.", option_1: nil, option_2: nil},
  {program_id: 4, day: 53, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 54, description: "400m Sprint - 6 sets - Take full recovery between each", option_1: nil, option_2: nil},
  {program_id: 4, day: 55, description: nil, option_1: nil, option_2: nil},
  {program_id: 4, day: 56, description: nil, option_1: nil, option_2: nil}
])
Exercise.create!([
  {name: "1 Leg Glute Bridge", video: "http://youtu.be/4a95Eif8R0I"},
  {name: "1 Leg Squat", video: "http://youtu.be/_X421gYXZ3U"},
  {name: "Airborne Lunge", video: "http://youtu.be/rQ8oxNv4f8M"},
  {name: "A Push-Up", video: "http://youtu.be/h4pFpwSXuFA"},
  {name: "Bear Claw", video: "http://youtu.be/hXCwH7GWQBA"},
  {name: "Broad Jump", video: "http://youtu.be/ffxkGhSnB4Y"},
  {name: "Burpee", video: "http://youtu.be/aMnhI8P6ijw"},
  {name: "Box Blast", video: "http://youtu.be/AaGfyHYB7y8"},
  {name: "Close Grip Push-Up", video: "http://youtu.be/er4QyzKYrH8"},
  {name: "Front Bridge", video: "http://www.youtube.com/watch?v=fNrQqj49hmM"},
  {name: "Front Bridge Knee-To-Elbow", video: "http://youtu.be/Z6EXskY_nQw"},
  {name: "Front Bridge Knee-To-Elbow", video: "http://youtu.be/Z6EXskY_nQw"},
  {name: "Front Bridge - Hi/Low", video: "http://youtu.be/18OdmaEO-A4"},
  {name: "Front Bridge - Spread Eagle", video: "http://youtu.be/QIQnKdFz5xw"},
  {name: "Glute Bridge", video: "http://www.youtube.com/watch?v=XoSyjdemIko"},
  {name: "Glute Bridge - Marching", video: "http://youtu.be/uF-DzZlbKr0"},
  {name: "High Knee Skip - In Place", video: "http://youtu.be/EEGrjye9eag"},
  {name: "Hollow Sit", video: "http://www.youtube.com/watch?v=sYwm8VqAl2U"},
  {name: "I-T", video: "http://youtu.be/J5j-SyejqZw"},
  {name: "Jumping Jack", video: "http://www.youtube.com/watch?v=aUHZeLYA6VU"},
  {name: "Lateral Bound", video: "http://youtu.be/QcQ9w0O3ujw"},
  {name: "Lateral Lunge", video: "http://youtu.be/45efi4CgFsw"},
  {name: "Leg Raise", video: "http://youtu.be/9KUb52nTnhw"},
  {name: "Mountain Climber", video: "http://youtu.be/zEplDzou308"},
  {name: "Pistol Squat", video: "http://youtu.be/dejEOHNkPzs"},
  {name: "Push-Up", video: "http://www.youtube.com/watch?v=nwhO5fuN8kE"},
  {name: "Reverse Lunge", video: "http://www.youtube.com/watch?v=7EPImHHY49c"},
  {name: "Reverse Lunge - Right Leg", video: "http://www.youtube.com/watch?v=7EPImHHY49c"},
  {name: "Reverse Lunge - Left Leg", video: "http://www.youtube.com/watch?v=7EPImHHY49c"},
  {name: "Shoulder Taps", video: "http://youtu.be/h-9G-zACYho"},
  {name: "Side Bridge", video: "http://www.youtube.com/watch?v=yXYJxo7A9h0"},
  {name: "Side Bridge - Knee Tuck", video: "http://youtu.be/LUil8oZopg8"},
  {name: "Side Bridge - Leg Lift", video: "http://youtu.be/VZr_2ZdkyQQ"},
  {name: "Split Squat Jump", video: "http://www.youtube.com/watch?v=bry_0XMxQKg"},
  {name: "Split Squat RFE", video: "http://youtu.be/J6G2mAHiL3A"},
  {name: "Squat", video: "http://www.youtube.com/watch?v=-J8OOtEqFtg"},
  {name: "Squat Jump", video: "http://www.youtube.com/watch?v=0fNHXgseCtI"},
  {name: "Step Run", video: "http://www.youtube.com/watch?v=t5PY1zlTNF4"},
  {name: "Suitcase Crunch", video: "http://youtu.be/Btd5NSScfSg"},
  {name: "Superman", video: "http://youtu.be/n4bGLnAyyqY"},
  {name: "V-Up", video: "http://www.youtube.com/watch?v=oFtdpmN7kJ4"},
  {name: "W", video: "http://www.youtube.com/watch?v=rLTP7HCUlMg"},
  {name: "Y", video: "http://www.youtube.com/watch?v=o4R-lG5wUSA"},
  {name: "Y-W", video: "http://youtu.be/mRix5boe6AQ"}
])
Program.create!([
  {name: "Shredzilla"},
  {name: "Beastzilla"},
  {name: "Fitzilla"},
  {name: "Strongzilla"}
])
Team.create!([
  {challenge_id: 1, program_id: 1, name: "Team Wes"},
  {challenge_id: 1, program_id: 2, name: "Team Jordan"},
  {challenge_id: 1, program_id: 4, name: "Team Tex"},
  {challenge_id: nil, program_id: nil, name: "Team David"}
])
Workout.create!([
  {day_id: 1, exercise_id: 36, hold: "1 sec", reps: "20", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 1, exercise_id: 36, hold: "30 sec*", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 1, exercise_id: 26, hold: "1 sec", reps: "10", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 1, exercise_id: 26, hold: "15 sec*", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 1, exercise_id: 31, hold: "30 sec", reps: "1 R/L", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 1, exercise_id: 10, hold: "30 sec", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 1, exercise_id: 43, hold: "15 sec", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 2, exercise_id: 28, hold: "15 sec*", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 2, exercise_id: 27, hold: "1 sec", reps: "10 R/L", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 2, exercise_id: 29, hold: "15 sec*", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 2, exercise_id: 15, hold: "1 sec", reps: "20", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 2, exercise_id: 18, hold: "15 sec", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 2, exercise_id: 41, hold: "X", reps: "10", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 2, exercise_id: 42, hold: "15 sec", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 4, exercise_id: 20, hold: "X", reps: "20", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 4, exercise_id: 37, hold: "X", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 4, exercise_id: 20, hold: "X", reps: "20", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 4, exercise_id: 26, hold: "1 sec", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 6, exercise_id: 34, hold: "1 sec", reps: "10 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 6, exercise_id: 38, hold: "X", reps: "20 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 6, exercise_id: 38, hold: "X", reps: "20 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 6, exercise_id: 42, hold: "1 sec", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 8, exercise_id: 2, hold: "1 sec", reps: "5 R/L", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 8, exercise_id: 36, hold: "1 sec", reps: "20", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 8, exercise_id: 9, hold: "1 sec", reps: "10", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 8, exercise_id: 19, hold: "1 sec", reps: "10", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 8, exercise_id: 5, hold: "3 sec", reps: "5 R/L", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 8, exercise_id: 32, hold: "1 sec", reps: "10 R/L", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 8, exercise_id: 1, hold: "3 sec", reps: "5 R/L", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 9, exercise_id: 35, hold: "1 sec", reps: "10 R/L", sets: "4", timer: ":30 Sec Rest Between Sets"},
  {day_id: 9, exercise_id: 26, hold: "1 sec", reps: "15", sets: "4", timer: ":30 Sec Rest Between Sets"},
  {day_id: 9, exercise_id: 22, hold: "1 sec", reps: "10 R/L", sets: "4", timer: ":30 Sec Rest Between Sets"},
  {day_id: 9, exercise_id: 44, hold: "1 sec", reps: "10", sets: "4", timer: ":30 Sec Rest Between Sets"},
  {day_id: 9, exercise_id: 18, hold: "15 sec", reps: "1", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 9, exercise_id: 41, hold: "X", reps: "10", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 9, exercise_id: 30, hold: "3 sec", reps: "5 R/L", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 11, exercise_id: 20, hold: "X", reps: "20", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 11, exercise_id: 37, hold: "X", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 11, exercise_id: 20, hold: "X", reps: "20", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 11, exercise_id: 26, hold: "X", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 13, exercise_id: 38, hold: "X", reps: "20 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 13, exercise_id: 34, hold: "X", reps: "10 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 13, exercise_id: 38, hold: "X", reps: "20 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 13, exercise_id: 42, hold: "X", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 57, exercise_id: 36, hold: "1 sec", reps: "20", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 57, exercise_id: 36, hold: "30 sec*", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 57, exercise_id: 26, hold: "1 sec", reps: "10", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 57, exercise_id: 26, hold: "15 sec*", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 57, exercise_id: 31, hold: "30 sec", reps: "1 R/L", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 57, exercise_id: 10, hold: "30 sec", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 57, exercise_id: 43, hold: "15 sec", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 58, exercise_id: 28, hold: "15 sec*", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 58, exercise_id: 27, hold: "1 sec", reps: "10 R/L", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 58, exercise_id: 29, hold: "15 sec*", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 58, exercise_id: 15, hold: "1 sec", reps: "20", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 58, exercise_id: 18, hold: "15 sec", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 58, exercise_id: 41, hold: "X", reps: "10", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 58, exercise_id: 42, hold: "15 sec", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 60, exercise_id: 20, hold: "X", reps: "20", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 60, exercise_id: 37, hold: "X", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 60, exercise_id: 20, hold: "X", reps: "20", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 60, exercise_id: 26, hold: "1 sec", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 62, exercise_id: 34, hold: "1 sec", reps: "10 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 62, exercise_id: 38, hold: "X", reps: "20 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 62, exercise_id: 38, hold: "X", reps: "20 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 62, exercise_id: 42, hold: "1 sec", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 64, exercise_id: 2, hold: "1 sec", reps: "5 R/L", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 64, exercise_id: 36, hold: "1 sec", reps: "20", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 64, exercise_id: 9, hold: "1 sec", reps: "10", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 64, exercise_id: 19, hold: "1 sec", reps: "10", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 64, exercise_id: 5, hold: "3 sec", reps: "5 R/L", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 64, exercise_id: 32, hold: "1 sec", reps: "10 R/L", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 64, exercise_id: 1, hold: "3 sec", reps: "5 R/L", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 65, exercise_id: 35, hold: "1 sec", reps: "10 R/L", sets: "4", timer: ":30 Sec Rest Between Sets"},
  {day_id: 65, exercise_id: 26, hold: "1 sec", reps: "15", sets: "4", timer: ":30 Sec Rest Between Sets"},
  {day_id: 65, exercise_id: 22, hold: "1 sec", reps: "10 R/L", sets: "4", timer: ":30 Sec Rest Between Sets"},
  {day_id: 65, exercise_id: 44, hold: "1 sec", reps: "10", sets: "4", timer: ":30 Sec Rest Between Sets"},
  {day_id: 65, exercise_id: 18, hold: "15 sec", reps: "1", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 65, exercise_id: 41, hold: "X", reps: "10", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 65, exercise_id: 30, hold: "3 sec", reps: "5 R/L", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 67, exercise_id: 20, hold: "X", reps: "20", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 67, exercise_id: 37, hold: "X", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 67, exercise_id: 20, hold: "X", reps: "20", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 67, exercise_id: 26, hold: "X", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 69, exercise_id: 38, hold: "X", reps: "20 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 69, exercise_id: 34, hold: "X", reps: "10 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 69, exercise_id: 38, hold: "X", reps: "20 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 69, exercise_id: 42, hold: "X", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 113, exercise_id: 36, hold: "1 sec", reps: "20", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 113, exercise_id: 36, hold: "30 sec*", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 113, exercise_id: 26, hold: "1 sec", reps: "10", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 113, exercise_id: 26, hold: "15 sec*", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 113, exercise_id: 31, hold: "30 sec", reps: "1 R/L", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 113, exercise_id: 10, hold: "30 sec", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 113, exercise_id: 43, hold: "15 sec", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 114, exercise_id: 28, hold: "15 sec*", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 114, exercise_id: 27, hold: "1 sec", reps: "10 R/L", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 114, exercise_id: 29, hold: "15 sec*", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 114, exercise_id: 15, hold: "1 sec", reps: "20", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 114, exercise_id: 18, hold: "15 sec", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 114, exercise_id: 41, hold: "X", reps: "10", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 114, exercise_id: 42, hold: "15 sec", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 116, exercise_id: 20, hold: "X", reps: "20", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 116, exercise_id: 37, hold: "X", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 116, exercise_id: 20, hold: "X", reps: "20", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 116, exercise_id: 26, hold: "1 sec", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 118, exercise_id: 34, hold: "1 sec", reps: "10 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 118, exercise_id: 38, hold: "X", reps: "20 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 118, exercise_id: 38, hold: "X", reps: "20 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 118, exercise_id: 42, hold: "1 sec", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 120, exercise_id: 2, hold: "1 sec", reps: "5 R/L", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 120, exercise_id: 36, hold: "1 sec", reps: "20", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 120, exercise_id: 9, hold: "1 sec", reps: "10", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 120, exercise_id: 19, hold: "1 sec", reps: "10", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 120, exercise_id: 5, hold: "3 sec", reps: "5 R/L", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 120, exercise_id: 32, hold: "1 sec", reps: "10 R/L", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 120, exercise_id: 1, hold: "3 sec", reps: "5 R/L", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 121, exercise_id: 35, hold: "1 sec", reps: "10 R/L", sets: "4", timer: ":30 Sec Rest Between Sets"},
  {day_id: 121, exercise_id: 26, hold: "1 sec", reps: "15", sets: "4", timer: ":30 Sec Rest Between Sets"},
  {day_id: 121, exercise_id: 22, hold: "1 sec", reps: "10 R/L", sets: "4", timer: ":30 Sec Rest Between Sets"},
  {day_id: 121, exercise_id: 44, hold: "1 sec", reps: "10", sets: "4", timer: ":30 Sec Rest Between Sets"},
  {day_id: 121, exercise_id: 18, hold: "15 sec", reps: "1", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 121, exercise_id: 41, hold: "X", reps: "10", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 121, exercise_id: 30, hold: "3 sec", reps: "5 R/L", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 123, exercise_id: 20, hold: "X", reps: "20", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 123, exercise_id: 37, hold: "X", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 123, exercise_id: 20, hold: "X", reps: "20", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 123, exercise_id: 26, hold: "X", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 124, exercise_id: 38, hold: "X", reps: "20 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 124, exercise_id: 34, hold: "X", reps: "10 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 124, exercise_id: 38, hold: "X", reps: "20 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 124, exercise_id: 42, hold: "X", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 169, exercise_id: 36, hold: "1 sec", reps: "20", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 169, exercise_id: 36, hold: "30 sec*", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 169, exercise_id: 26, hold: "1 sec", reps: "10", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 169, exercise_id: 26, hold: "15 sec*", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 169, exercise_id: 31, hold: "30 sec", reps: "1 R/L", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 169, exercise_id: 10, hold: "30 sec", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 169, exercise_id: 43, hold: "15 sec", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 170, exercise_id: 28, hold: "15 sec*", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 170, exercise_id: 27, hold: "1 sec", reps: "10 R/L", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 170, exercise_id: 29, hold: "15 sec*", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 170, exercise_id: 15, hold: "1 sec", reps: "20", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 170, exercise_id: 18, hold: "15 sec", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 170, exercise_id: 41, hold: "X", reps: "10", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 170, exercise_id: 42, hold: "15 sec", reps: "1", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 172, exercise_id: 20, hold: "X", reps: "20", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 172, exercise_id: 37, hold: "X", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 172, exercise_id: 20, hold: "X", reps: "20", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 172, exercise_id: 26, hold: "1 sec", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 174, exercise_id: 34, hold: "1 sec", reps: "10 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 174, exercise_id: 38, hold: "X", reps: "20 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 174, exercise_id: 38, hold: "X", reps: "20 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 174, exercise_id: 42, hold: "1 sec", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 176, exercise_id: 2, hold: "1 sec", reps: "5 R/L", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 176, exercise_id: 36, hold: "1 sec", reps: "20", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 176, exercise_id: 9, hold: "1 sec", reps: "10", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 176, exercise_id: 19, hold: "1 sec", reps: "10", sets: "4", timer: ":30 Rest Between Sets"},
  {day_id: 176, exercise_id: 5, hold: "3 sec", reps: "5 R/L", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 176, exercise_id: 32, hold: "1 sec", reps: "10 R/L", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 176, exercise_id: 1, hold: "3 sec", reps: "5 R/L", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 177, exercise_id: 35, hold: "1 sec", reps: "10 R/L", sets: "4", timer: ":30 Sec Rest Between Sets"},
  {day_id: 177, exercise_id: 26, hold: "1 sec", reps: "15", sets: "4", timer: ":30 Sec Rest Between Sets"},
  {day_id: 177, exercise_id: 22, hold: "1 sec", reps: "10 R/L", sets: "4", timer: ":30 Sec Rest Between Sets"},
  {day_id: 177, exercise_id: 44, hold: "1 sec", reps: "10", sets: "4", timer: ":30 Sec Rest Between Sets"},
  {day_id: 177, exercise_id: 18, hold: "15 sec", reps: "1", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 177, exercise_id: 41, hold: "X", reps: "10", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 177, exercise_id: 30, hold: "3 sec", reps: "5 R/L", sets: "3", timer: ":15 Sec Rest Between Sets"},
  {day_id: 179, exercise_id: 20, hold: "X", reps: "20", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 179, exercise_id: 37, hold: "X", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 179, exercise_id: 20, hold: "X", reps: "20", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 179, exercise_id: 26, hold: "X", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 180, exercise_id: 38, hold: "X", reps: "20 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 180, exercise_id: 34, hold: "X", reps: "10 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 180, exercise_id: 38, hold: "X", reps: "20 R/L", sets: "As Many As Possible", timer: "10:00 Total"},
  {day_id: 180, exercise_id: 42, hold: "X", reps: "10", sets: "As Many As Possible", timer: "10:00 Total"}
])
Dailychallenge.create!([
  {day_id: 1, description: "Introduce yourself on Glide."}
])